/* salva.h generated by valac 0.28.0, the Vala compiler, do not modify */


#ifndef __SALVA_H__
#define __SALVA_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define SALVA_TYPE_ENTIDAD (salva_entidad_get_type ())
#define SALVA_ENTIDAD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SALVA_TYPE_ENTIDAD, SalvaEntidad))
#define SALVA_ENTIDAD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SALVA_TYPE_ENTIDAD, SalvaEntidadClass))
#define SALVA_IS_ENTIDAD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SALVA_TYPE_ENTIDAD))
#define SALVA_IS_ENTIDAD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SALVA_TYPE_ENTIDAD))
#define SALVA_ENTIDAD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SALVA_TYPE_ENTIDAD, SalvaEntidadClass))

typedef struct _SalvaEntidad SalvaEntidad;
typedef struct _SalvaEntidadClass SalvaEntidadClass;
typedef struct _SalvaEntidadPrivate SalvaEntidadPrivate;

struct _SalvaEntidad {
	GObject parent_instance;
	SalvaEntidadPrivate * priv;
};

struct _SalvaEntidadClass {
	GObjectClass parent_class;
};


GType salva_entidad_get_type (void) G_GNUC_CONST;
SalvaEntidad* salva_entidad_new (guint id);
SalvaEntidad* salva_entidad_construct (GType object_type, guint id);
GArray* salva_entidad_valores_para_query (SalvaEntidad* self);
guint salva_entidad_get_id (SalvaEntidad* self);
void salva_entidad_set_id (SalvaEntidad* self, guint value);


G_END_DECLS

#endif
