/* salva.vapi generated by valac 0.28.0, do not modify. */

namespace Salva {
	[CCode (cheader_filename = "salva.h")]
	public class Entidad : GLib.Object {
		public Entidad (uint id);
		public GLib.Array<string> valores_para_query ();
		public uint id { get; protected set; }
	}
}
